[[language]]
name = "rust"
auto-format = true
formatter = { command = "leptosfmt" , args = ["--stdin"] }
language-servers = ["rust-analyzer", "tailwindcss-ls"]

[language-server.rust-analyzer.config]
config = { procMacro = { ignored = { leptos_macro = [
  # Optional:
  # "component",
  "server",
] } } }

[language-server.tailwindcss-ls]
config = { userLanguages = { rust = "html", "*.rs" = "html" } }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "svelte"
language-servers = ["svelteserver", "tailwindcss-ls"]
